version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=hoangdz
      - xpack.security.enabled=true
    networks:
      - es-net
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200 
  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.17.7
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - xpack.security.enabled=true
        - xpack.encryptedSavedObjects.encryptionKey=grBEz5y0sFu2ZdpgkalCfETSOIiHknIr
        - ELASTIC_USERNAME=elastic
        - ELASTIC_PASSWORD=hoangdz
      volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        - es-net
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601
networks:
  es-net:
    driver: bridge