version: "3.3"

services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Path(`/`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
  
