version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "dbname"
      MYSQL_ROOT_PASSWORD: "tF8jtP#zdz"
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: